//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileExplorerApp.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        /// <summary>
        /// True = Dark mode, False = Light mode. Xem Helpers/AppTheme.cs va
        /// Forms/SettingsForm.cs (nhom "Giao dien").
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsDarkMode
        {
            get
            {
                return ((bool)(this["IsDarkMode"]));
            }
            set
            {
                this["IsDarkMode"] = value;
            }
        }

        /// <summary>Co hien file/thu muc an mac dinh khi mo ung dung khong.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHiddenFiles
        {
            get
            {
                return ((bool)(this["ShowHiddenFiles"]));
            }
            set
            {
                this["ShowHiddenFiles"] = value;
            }
        }

        /// <summary>
        /// Che do xem mac dinh cua lvwFiles, luu duoi dang gia tri int cua
        /// System.Windows.Forms.View (LargeIcon=0, SmallIcon=1, List=2, Details=3).
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultViewMode
        {
            get
            {
                return ((int)(this["DefaultViewMode"]));
            }
            set
            {
                this["DefaultViewMode"] = value;
            }
        }

        /// <summary>Bat/tat tu dong cap nhat khi thu muc thay doi (FileMonitorService).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRefreshEnabled
        {
            get
            {
                return ((bool)(this["AutoRefreshEnabled"]));
            }
            set
            {
                this["AutoRefreshEnabled"] = value;
            }
        }

        /// <summary>Do tre (ms) truoc khi lam moi sau khi FileMonitorService bao thay doi.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int WatcherDelayMs
        {
            get
            {
                return ((int)(this["WatcherDelayMs"]));
            }
            set
            {
                this["WatcherDelayMs"] = value;
            }
        }

        /// <summary>Bat/tat ghi nhat ky thao tac (LogService).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogEnabled
        {
            get
            {
                return ((bool)(this["LogEnabled"]));
            }
            set
            {
                this["LogEnabled"] = value;
            }
        }

        /// <summary>Thu muc luu file nhat ky (LogService).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%AppData%\\SFileManager\\logs")]
        public string LogPath
        {
            get
            {
                return ((string)(this["LogPath"]));
            }
            set
            {
                this["LogPath"] = value;
            }
        }

        /// <summary>Thu muc luu file baseline hash cua cac thu muc dang/da tung duoc giam sat (BaselineService).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%AppData%\\SFileManager\\baselines")]
        public string BaselinePath
        {
            get
            {
                return ((string)(this["BaselinePath"]));
            }
            set
            {
                this["BaselinePath"] = value;
            }
        }
    }
}
